# Generated by Django 4.1.7 on 2023-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=40)),
                ('thumbnail_url', models.FileField(upload_to='thumbnails')),
                ('file_url', models.FileField(upload_to='files')),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
