# Generated by Django 4.1.7 on 2023-03-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
