# Generated by Django 4.1.7 on 2023-03-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_file_url_file_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='thumbnail',
        ),
    ]
