# Generated by Django 4.1.7 on 2023-03-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_file_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
