# Generated by Django 4.1.7 on 2023-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_rename_file_customfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
