# Generated by Django 4.1.7 on 2023-03-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_customfile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfile',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
